### ISSUE TITLE
Can we use an asymmetric key pair instead of a p12 for iOS?

### ISSUE THREAD

**Issue by Tulakshana** [IBM-Swift/BlueSSLService#69]
I'm trying to avoid bundling the p12 with the app. For this I have created a public/private key pair,

```
    private var privateKey: SecKey?
    private var publicKey: SecKey?
    
    private func generateAsymmetricKeyPair() throws {
        let tag = "com.mycompany.keys.myapp".data(using: .utf8)!
        let attributes: [String: Any] =
            [kSecAttrKeyType as String:            kSecAttrKeyTypeRSA,
             kSecAttrKeySizeInBits as String:      2048,
             kSecPrivateKeyAttrs as String:
                [kSecAttrIsPermanent as String:    true,
                 kSecAttrApplicationTag as String: tag],
             kSecAttrIsExtractable as String: true
        ]
        
        var error: Unmanaged<CFError>?
        guard let key = SecKeyCreateRandomKey(attributes as CFDictionary, &error) else {
            throw error!.takeRetainedValue() as Error
        }
        publicKey = SecKeyCopyPublicKey(key)
        privateKey = key
    }

```

Is there a way to use this in BlueSSLService instead of a p12?

@niklassaers , has tried to avoid bundling the p12 sometime back,
https://github.com/IBM-Swift/BlueSSLService/issues/28

Can we use the constructor `init(withCipherSuite cipherSuite: String? = nil, clientAllowsSelfSignedCertificates: Bool = true)` in iOS?

According the documentation provided iOS apps require a p12 to work. Sorry for multiple questions. I'm in desperate need of help.

**Comment by billabt** [comment]
You should be able to use that _init_ function but you'll have to **provide your own verification function** using the hook that's provided on _both the server side and the client_.  The callback hook is documented in the **README**.  But, take note, you'll have to have _relatively deep knowledge_ of _Apple's Secure Transport_ in order to make it work.  Here's the relevant documentation from the **README**:

### Extending Connection Verification

`SSLService` provides a callback mechanism should you need to specify **additional** verification logic. After creating the instance of `SSLService`, you can set the instance variable `verifyCallback`.  This instance variable has the following signature:
```
public var verifyCallback: ((_ service: SSLService) -> (Bool, String?))? = nil
```
Setting this callback is not required. It defaults to `nil` unless set.  The first parameter passed to your callback is the instance of `SSLService` that has this callback.  This will allow you to access the public members of the `SSLService` instance in order to do additional verification.  Upon completion, your callback should return a tuple.  The first value is a `Bool` indicating the sucess or failure of the routine.  The second value is an `optional String` value used to provide a description in the case where verification failed. In the event of callback failure, an `exception` will be thrown by the internal verification function.  **Important Note:** To effectively use this callback requires knowledge of the platforms underlying secure transport service, `Apple Secure Transport` on `supported Apple platforms` and `OpenSSL` on `Linux`.

This callback is called on the **server side** when the connection is has been accepted.  This takes place during the _acceptConnection()_ function in **BlueSocket**.  On the **client side** it's called when the **BlueSocket** _connect()_ function is called.

Also note that since you'll have provide _Secure Transport_ specific code in order to do the verification on _Apple Platforms_ you'd need to provide _OpenSSL_ specific code as well in the callback function should you decide to support **Linux**.  This'll complicate matters significantly if you need to support both.

The other alternative would be to provide a function in your app that, using an API such as _URLSession_, **downloads the .p12** when the app is first run and stores it locally.  This would avoid you having to bundle it with the app.  You could also then provide your own method of updating the **.p12** should that become necessary.  Using this method, you can avoid bundling the .p12 **as well as** delving into the depths of _Secure Transport_ and/or _OpenSSL_.

**Comment by Tulakshana** [comment]
Thank you so much.
